name: Sync Submodules

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Sync submodules'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
        token: ${{ secrets.MY_PAT_TOKEN }}

    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --init
        git submodule set-branch --branch dev kp
        git submodule update --remote --recursive --rebase --force
        git submodule status

    - name: Setup bot
      run: |
        git config user.name "Git bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add .
        git diff --cached --exit-code || git commit -m "Auto update submodules"
        git push origin master  # 使用 token 推送
